# Generated by Django 5.2.17 on 2026-09-24 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_naveridentity_naveroauthattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='naveroauthattempt',
            name='nickname',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='naveroauthattempt',
            name='provider_subject',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='MemberConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_accepted_at', models.DateTimeField()),
                ('privacy_accepted_at', models.DateTimeField()),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_consent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
