# Generated by Django 5.2.17 on 2026-09-24 05:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('body', models.TextField(blank=True)),
                ('category', models.CharField(default='notice', max_length=40)),
                ('original_url', models.URLField(blank=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('service_categories', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('hours', models.CharField(blank=True, max_length=160)),
                ('cafe_url', models.URLField(blank=True)),
                ('map_url', models.URLField(blank=True)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('redemption_instructions', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.partner')),
            ],
            options={
                'ordering': ['-starts_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=40)),
                ('model_name', models.CharField(max_length=80)),
                ('generation', models.CharField(blank=True, max_length=40)),
                ('model_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.vehicle')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fuel', '주유'), ('service', '정비'), ('part', '소모품'), ('wash', '세차'), ('other', '기타')], max_length=16)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_krw', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(blank=True, max_length=160)),
                ('quantity_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.vehicle')),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
    ]
