# Generated by Django 5.2.17 on 2026-10-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_partner_same_name_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='naveridentity',
            name='age',
            field=models.CharField(blank=True, max_length=32, verbose_name='연령대'),
        ),
        migrations.AddField(
            model_name='naveridentity',
            name='birthday',
            field=models.CharField(blank=True, max_length=16, verbose_name='생일'),
        ),
        migrations.AddField(
            model_name='naveridentity',
            name='birthyear',
            field=models.CharField(blank=True, max_length=8, verbose_name='출생연도'),
        ),
        migrations.AddField(
            model_name='naveridentity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='연락처 이메일 주소'),
        ),
        migrations.AddField(
            model_name='naveridentity',
            name='gender',
            field=models.CharField(blank=True, max_length=16, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='naveridentity',
            name='mobile',
            field=models.CharField(blank=True, max_length=32, verbose_name='휴대전화번호'),
        ),
        migrations.AddField(
            model_name='naveridentity',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='회원 이름'),
        ),
        migrations.AddField(
            model_name='naveridentity',
            name='profile_image',
            field=models.URLField(blank=True, max_length=2048, verbose_name='프로필 사진'),
        ),
        migrations.AddField(
            model_name='naveroauthattempt',
            name='profile_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='partnerstaff',
            name='can_manage_bookings',
            field=models.BooleanField(default=False, help_text='소속 업체의 예약을 확인하고 처리할 수 있습니다.'),
        ),
        migrations.AlterField(
            model_name='partnerstaff',
            name='can_verify_records',
            field=models.BooleanField(default=False, help_text='담당자가 앱에서 QR로 차량을 조회하고 업체 인증 정비기록을 등록할 수 있습니다.'),
        ),
        migrations.AlterField(
            model_name='partnerstaff',
            name='is_active',
            field=models.BooleanField(default=True, help_text='담당자와 소속 업체가 모두 활성화되어야 협력업체 등급으로 인식합니다.'),
        ),
    ]
