# Generated by Django 5.2.17 on 2026-10-04 10:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_season_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='제목')),
                ('kind', models.CharField(choices=[('banner', '홈 제휴 배너'), ('product', '쇼핑 상품')], max_length=16, verbose_name='노출 위치')),
                ('category', models.CharField(choices=[('recommended', '추천 상품'), ('groupbuy', '공동 구매'), ('benefits', '회원 혜택')], default='recommended', max_length=24, verbose_name='상품 분류')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('image_url', models.URLField(blank=True, max_length=2048, verbose_name='공개 HTTPS 이미지')),
                ('asset_key', models.CharField(blank=True, choices=[('mini-october', 'MINI 10월 프로모션'), ('phone-holder', '거치대'), ('grille-parts', '그릴 부품'), ('shift-knob', '기어 노브')], max_length=40, verbose_name='내장 이미지')),
                ('action_url', models.URLField(blank=True, max_length=2048, verbose_name='구매·안내 HTTPS 주소')),
                ('price_krw', models.PositiveIntegerField(blank=True, null=True, verbose_name='판매 금액(원)')),
                ('compatible_models', models.CharField(blank=True, max_length=240, verbose_name='호환 차량')),
                ('is_active', models.BooleanField(default=False, verbose_name='공개')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='노출 시작')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='노출 종료')),
                ('display_order', models.PositiveSmallIntegerField(default=100, verbose_name='표시 순서')),
            ],
            options={
                'verbose_name': '앱 배너·쇼핑 상품',
                'verbose_name_plural': '앱 배너·쇼핑 상품',
                'ordering': ['display_order', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=12, unique=True, verbose_name='플랫폼')),
                ('version', models.CharField(max_length=32, verbose_name='최신 버전')),
                ('build_number', models.PositiveBigIntegerField(verbose_name='최신 빌드 번호')),
                ('download_url', models.URLField(blank=True, max_length=2048, verbose_name='업데이트 안내·스토어 HTTPS 주소')),
                ('notes', models.TextField(blank=True, verbose_name='변경 내용')),
                ('is_active', models.BooleanField(default=False, verbose_name='업데이트 안내 활성화')),
            ],
            options={
                'verbose_name': '앱 업데이트 안내',
                'verbose_name_plural': '앱 업데이트 안내',
            },
        ),
        migrations.AddField(
            model_name='seasonbanner',
            name='asset_key',
            field=models.CharField(blank=True, choices=[('mini-october', 'MINI 10월 프로모션')], max_length=40, verbose_name='내장 배너'),
        ),
        migrations.AlterField(
            model_name='seasonbanner',
            name='image_url',
            field=models.URLField(blank=True, help_text='공개 HTTPS 이미지 주소. 비워두면 선택한 내장 배너를 사용하며, 내장 배너도 없으면 브랜드 안내만 표시합니다.', max_length=2048, verbose_name='배너 이미지 주소'),
        ),
        migrations.CreateModel(
            name='MemberPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle', verbose_name='대표 차량')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_preference', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '회원 대표 차량',
                'verbose_name_plural': '회원 대표 차량',
            },
        ),
        migrations.CreateModel(
            name='RecordCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=240, verbose_name='정정 요청 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청 시각')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 시각')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='core.ledgerentry', verbose_name='원본 기록')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='요청 회원')),
                ('resolved_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_requests', to='core.ledgerentry', verbose_name='연결된 정정 기록')),
            ],
            options={
                'verbose_name': '정비 기록 정정 요청',
                'verbose_name_plural': '정비 기록 정정 요청',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('entry', 'requested_by'), name='one_open_record_correction')],
            },
        ),
    ]
